name: data_uploader_hourly_7am_10pm_ET

on:
  # fire every hour on the hour (UTC)
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      - name: Time gate (run only 07–22 America/New_York)
        id: timegate
        run: |
          HOUR_NY=$(TZ=America/New_York date +%H)
          echo "Local NY hour: $HOUR_NY"
          if [ "$HOUR_NY" -ge 7 ] && [ "$HOUR_NY" -le 22 ]; then
            echo "run=true" >> $GITHUB_OUTPUT
          else
            echo "run=false" >> $GITHUB_OUTPUT
            echo "Outside 07–22 NY window. Skipping."
          fi

      - uses: actions/checkout@v4
        if: steps.timegate.outputs.run == 'true'

      - uses: actions/setup-python@v5
        if: steps.timegate.outputs.run == 'true'
        with:
          python-version: "3.11"

      - name: Install deps
        if: steps.timegate.outputs.run == 'true'
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            echo "requirements.txt not found; installing minimal deps…"
            pip install cfbd pandas numpy SQLAlchemy pg8000 python-dotenv certifi filelock
          fi

      - name: Debug versions (optional)
        if: steps.timegate.outputs.run == 'true'
        run: |
          python -c "import sys, pandas, sqlalchemy, cfbd; print('py', sys.version); print('pandas', pandas.__version__); print('sqlalchemy', sqlalchemy.__version__); print('cfbd', cfbd.__version__)"

      - name: Run uploader
        if: steps.timegate.outputs.run == 'true'
        run: python data_uploader.py
