- name: Run uploader
  env:
    BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
    DATABASE_URL: ${{ secrets.DATABASE_URL }}   # or the NEON_* ones your script expects
  run: python data_uploader.py
  
on:
  schedule:
    - cron: "10 13 * * *"   # 09:10 ET (cron uses UTC)
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            echo "requirements.txt not found; installing minimal deps…"
            pip install \
              cfbd pandas numpy SQLAlchemy pg8000 python-dotenv certifi filelock
          fi

      - name: Debug versions (optional)
        run: |
          python -c "import sys, pandas, sqlalchemy, cfbd; print('py', sys.version); print('pandas', pandas.__version__); print('sqlalchemy', sqlalchemy.__version__); print('cfbd', cfbd.__version__)"
      
      - name: Run uploader
        env:
          BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}   # or NEON_* pieces if your script expects them
        run: python data_uploader.py
